"""initial_schema

Revision ID: c38112fb7708
Revises: 
Create Date: 2025-12-30 01:25:16.685053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38112fb7708'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_job_listing_platform_external_id')
    )
    op.create_index(op.f('ix_job_listings_external_id'), 'job_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_job_listings_id'), 'job_listings', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('current_job_title', sa.String(length=255), nullable=True),
    sa.Column('target_job_title', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('salary_expectation', sa.Integer(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('resume_base64', sa.Text(), nullable=True),
    sa.Column('resume_parsed_data', sa.JSON(), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('encrypted_linkedin_email', sa.Text(), nullable=True),
    sa.Column('encrypted_linkedin_password', sa.Text(), nullable=True),
    sa.Column('job_title_priority_1', sa.String(length=255), nullable=True),
    sa.Column('job_title_priority_2', sa.String(length=255), nullable=True),
    sa.Column('job_title_priority_3', sa.String(length=255), nullable=True),
    sa.Column('exp_years_internship', sa.Integer(), nullable=True),
    sa.Column('exp_years_entry_level', sa.Integer(), nullable=True),
    sa.Column('exp_years_associate', sa.Integer(), nullable=True),
    sa.Column('exp_years_mid_senior_level', sa.Integer(), nullable=True),
    sa.Column('exp_years_director', sa.Integer(), nullable=True),
    sa.Column('exp_years_executive', sa.Integer(), nullable=True),
    sa.Column('pref_onsite', sa.Integer(), nullable=True),
    sa.Column('pref_hybrid', sa.Integer(), nullable=True),
    sa.Column('pref_remote', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resume_url', sa.String(length=500), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('source_application_id', sa.String(length=255), nullable=True),
    sa.Column('confirmation_email', sa.String(length=500), nullable=True),
    sa.Column('last_status_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('linkedin_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_encrypted', sa.String(length=500), nullable=False),
    sa.Column('password_encrypted', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_credentials_id'), 'linkedin_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_linkedin_credentials_user_id'), 'linkedin_credentials', ['user_id'], unique=True)
    op.create_table('user_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_jobs_id'), 'user_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_user_jobs_job_id'), 'user_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_user_jobs_user_id'), 'user_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_jobs_user_id'), table_name='user_jobs')
    op.drop_index(op.f('ix_user_jobs_job_id'), table_name='user_jobs')
    op.drop_index(op.f('ix_user_jobs_id'), table_name='user_jobs')
    op.drop_table('user_jobs')
    op.drop_index(op.f('ix_linkedin_credentials_user_id'), table_name='linkedin_credentials')
    op.drop_index(op.f('ix_linkedin_credentials_id'), table_name='linkedin_credentials')
    op.drop_table('linkedin_credentials')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_listings_id'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_external_id'), table_name='job_listings')
    op.drop_table('job_listings')
    # ### end Alembic commands ###
